version: "3"
services:
  jekyll:
    container_name: "github_jekyll"
    image: "jekyll/jekyll:3"
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - "4000:4000"
    volumes:
      - "./:/srv/jekyll"
